# Task 1: Create a Simple Workflow with Push Trigger
#     Objective: Create a workflow that runs automatically when you push code to your repository.
#     Steps:
#         Create a .github/workflows/main.yml file in your repository.
#         Define a workflow that runs on the push event.
#         Use the actions/checkout action from GitHub Marketplace to checkout your repository.
#         Add a simple step, such as running a shell command (echo), to confirm the workflow executes successfully.
#     Key Concepts: Workflow trigger, action from GitHub Marketplace.

name: "task 1"
on: [push]

jobs:
    checkout_code:
        runs-on: ubuntu_latest
        steps:
            - name: "first step"
              uses: actions/checkout@v4
              timeout-minutes: 0.5
              continue-on-error: true # Default is true, but only for better readibilit
                
    show_echo:
        runs-on: macos_latest
        steps:
            - name: showing echo
              run: echo "Hello World"
              timeout-minutes: 0.5
