name: test me

on: [push]

jobs:
    first:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          id: checkout
          uses: actions/checkout@v3

        - name: Test Local Action
          id: test-action
          uses: ./
          with:
          who-to-greet: Mona Lisa Octocat

        - name: Print Output
          id: output
          run: echo "${{ steps.test-action.outputs.greeting }}"